travis:
  secure:
    BINSTAR_TOKEN: kp3EOSIzIOlSefpivMDbgkz0frsJWRDSihF0s27zPKBKzWXqcSR/DczZ1CoaX/PgYNNyQ5tEvPBELHwGmngWis1YzplaQDsgFVXz3XseL7sgmLaV/jCg/dJ8J89quBTRQXmF6qmxwSzKtGs+07hdcXGjPI3/tLXo+PBsGw4KIbnTUacFaMEik+pcu/Xofp1zoMne+JOxBrB+LQ9wNXYB4pgXACBpecYUi/OegM0ViT6zUzsrxuDlQktJjdXaTODCUm09gqAoNws4EJc+PUNjeabVUsk0Gxso/wylpiMzCtxRIXVa/VAYH0AZvHVF6S/fBoY+L3orbvvgv7QpEvUPjU0vLmyRI07kl7rGM0NWKG9rDdqeZKD2pwsG7gLX5BcFDEtS7WmcFmWyTB604Hmp0Y8bSu4kZAY2jcugh2caX9iD441wHgXK8LOX0y77LgaKm2h2sicK0hrSq6zfUiywOqGjmrLq60Lq5MRLLTzXBJb5A7gWov2pTYE86tc+hh77oZZrVc2b3mDhwnjKMKCyOfP5Q5qarsIdjzS0wdhQi7psPM1eupfKU21Xziz5DxB+5GN5g8aMIXKHc2C8jdJ8Y4QVYQAoXWZNYPv+mh7i+N/jMvAMNXt6BvOYUT+8SgAhAwVHrCNHXbPXQZLlXjiy4zkbHuwLqGQyuadc/9+Wiks=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
